version: '3.8'

services:
  api:
    container_name: wsmcbl.api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=mydb;User Id=myuser;Password=mypassword;
      - ASPNETCORE_ENVIRONMENT=Test
    depends_on:
      - db
    networks:
      - network-test
    command: ["sh", "-c", "dotnet ef database update && dotnet wsmcbl.src.dll"]

  db:
    container_name: database
    build:
      context: .
      dockerfile: postgres/Dockerfile
    ports:
      - "5432:5432"
    networks:
      - network-test
    
    
networks:
  network-test:
    external: true