version: '3.8'

services:
  
  database-test:
    image: postgres:14
    container_name: database-test
    environment:
      - POSTGRES_DB=wsmcbl_database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass12345
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - test-network

  api-test:
    build:
      context: .
      dockerfile: ./config/dotnet/Test.Dockerfile
    container_name: api-test
    environment:
      - SONAR_TOKEN=${SONAR_TOKEN}
      - ASPNETCORE_ENVIRONMENT=Test
      - ConnectionStrings__DefaultConnection=Host=database-test;Database=wsmcbl_database;Username=user;Password=pass12345
    depends_on:
      - database-test
    networks:
      - test-network
    command: bash -c "make dn-ss"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./Makefile:/app/Makefile
      - ./wsmcbl.back.sln:/app/wsmcbl.back.sln
      - nuget-packages:/root/.nuget/packages
        
        
volumes:
  nuget-packages:

networks:
  test-network: