version: '3.8'

services:
  
  api:
    build:
      context: .
      dockerfile: tests/config/postgres/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
    ports:
      - 5000:80
      - 5001:443
        
        
  db:
    container_name: database
    build:
      context: .
      dockerfile: tests/config/postgres/Dockerfile
    ports:
      - "5432:5432"
    networks:
      - network-test
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    
    
networks:
  network-test:
    external: true