services:
  
  database:
    image: postgres:14
    container_name: database
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - database-volume:/var/lib/postgresql/data
      - postgres_backups:/var/lib/postgresql/backups
    networks:
      - app-network
  
  api:
    build:
      context: .
      dockerfile: ./config/dotnet/Dockerfile
    restart: unless-stopped
    container_name: api
    environment:
      - ConnectionStrings__DefaultConnection=Host=database;Database=${DATABASE_NAME};Username=${DATABASE_USER};Password=${DATABASE_PASSWORD}
      - Resource_Directory=resource
      - JWT_KEY=${JWT_KEY}
      - POSTE_URL=${POSTE_URL}
      - NEXTCLOUD_URL=${NEXTCLOUD_URL}
      - NEXTCLOUD_USERNAME=${NEXTCLOUD_USERNAME}
      - NEXTCLOUD_PASSWORD=${NEXTCLOUD_PASSWORD}
      - INFO_EMAIL_PASSWORD=${INFO_EMAIL_PASSWORD}
    ports:
      - '4000:8080'
    depends_on:
      - database
    networks:
      - app-network
    volumes:
      - postgres_backups:/backups

volumes:
  database-volume:
  postgres_backups:
    
networks:
  app-network:
    external: true
