version: '3.8'

services:
  
  dotnet-base:
    build:
      context: .
      dockerfile: ./config/dotnet/Base.Dockerfile
    container_name: dotnet-base
    image: dotnet-base

  database:
    image: postgres:14
    container_name: database
    environment:
      - POSTGRES_DB=wsmcbl_database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass12345
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - database-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
  
  api:
    build:
      context: .
      dockerfile: ./config/dotnet/Dockerfile
    image: dotnet-base
    restart: unless-stopped
    container_name: api
    environment:
      - ConnectionStrings__DefaultConnection=Host=database;Database=wsmcbl_database;Username=user;Password=pass12345
    depends_on:
      - dotnet-base
      - database
    networks:
      - app-network
      
  
  nginx:
    build:
      context: ./config/nginx
    container_name: nginx
    ports:
      - "4000:80"
    depends_on:
      - api
    networks:
      - app-network
        
        
        
  


  
  database-test:
    image: postgres:14
    container_name: database-test
    environment:
      - POSTGRES_DB=database_test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass12345
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - /dev/shm
    ports:
      - "5400:5400"
    networks:
      - app-network

  api-test:
    build:
      context: .
      dockerfile: ./config/dotnet/Test.Dockerfile
    image: dotnet-base
    container_name: api-test
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
      - ConnectionStrings__DefaultConnection=Host=database-test;Database=database_test;Username=user;Password=pass12345
    depends_on:
      - dotnet-base
      - database-test
    networks:
      - app-network
    ports:
      - "5001:80"
    command: bash -c "dotnet test"

volumes:
  database-volume:
    
networks:
  app-network:
    driver: bridge