version: '3.8'

services:
  
  database-test:
    image: postgres:14
    container_name: database-test
    environment:
      - POSTGRES_DB=wsmcbl_database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass12345
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - test-network

  api-test:
    build:
      context: .
      dockerfile: ./config/dotnet/Test.Dockerfile
    container_name: api-test
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
      - ConnectionStrings__DefaultConnection=Host=database-test;Database=wsmcbl_database;Username=user;Password=pass12345
    depends_on:
      - database-test
    networks:
      - test-network
    command: bash -c "dotnet test --filter "EnrollStudentActionsTest""
    volumes:
      - ./src:/app/src               # Monta el directorio de código fuente local
      - ./tests:/app/tests           # Monta el directorio de tests local
      - ./*.sln:/app/*.sln


networks:
  test-network: