services:

  database:
    image: postgres:14
    container_name: database
    environment:
      - POSTGRES_DB=wsmcbl_database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass12345
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - database-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
  
  api:
    build:
      context: .
      dockerfile: ./config/dotnet/Dockerfile
    restart: unless-stopped
    container_name: api
    environment:
      - ConnectionStrings__DefaultConnection=Host=database;Database=wsmcbl_database;Username=user;Password=pass12345
      - Resource_Directory=resource
      - JWT_KEY=${JWT_KEY}
    depends_on:
      - database
    networks:
      - app-network
      
  nginx2:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - app-network

volumes:
  database-volume:
    
networks:
  app-network:
    external: true
