services:
  
  api-test:
    build:
      context: .
      dockerfile: ./config/dotnet/Test.Dockerfile
    container_name: api-test
    environment:
      - SONAR_TOKEN=${SONAR_TOKEN}
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./wsmcbl.back.sln:/app/wsmcbl.back.sln
      - .:/app/coverage
    command: >
      sh -c "dotnet-coverage collect 'dotnet test' -f xml -o 'coverage.xml' &&
         cp coverage.xml /app/coverage/ && cd coverage &&
         chown 1000:1000 coverage.xml && \
         chmod 644 coverage.xml"
