services:
  
  database_restore:
    image: postgres:14
    container_name: database_restore
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - ./backup.sql:/backup.sql
      - database-volume:/var/lib/postgresql/data
      - postgres_backups:/var/lib/postgresql/backups
  
  api:
    build:
      context: .
      dockerfile: ./config/dotnet/Dockerfile
    restart: unless-stopped
    container_name: api
    environment:
      - ConnectionStrings__DefaultConnection=Host=database_restore;Database=${DATABASE_NAME};Username=${DATABASE_USER};Password=${DATABASE_PASSWORD}
      - Resource_Directory=resource
      - JWT_KEY=${JWT_KEY}
      - POSTE_URL=${POSTE_URL}
      - NEXTCLOUD_URL=${NEXTCLOUD_URL}
      - NEXTCLOUD_USERNAME=${NEXTCLOUD_USERNAME}
      - NEXTCLOUD_PASSWORD=${NEXTCLOUD_PASSWORD}
      - INFO_EMAIL_PASSWORD=${INFO_EMAIL_PASSWORD}
      - API_ENVIRONMENT_MODE=${API_ENVIRONMENT_MODE}
    ports:
      - '4000:8080'
    depends_on:
      - database_restore
    networks:
      - app-network
    volumes:
      - postgres_backups:/backups

volumes:
  database-volume:
  postgres_backups:
    
networks:
  app-network:
    external: true