version: '3.6'

services:

  wsmcbl-web-be:
    container_name: wsmcbl-web-be
    build:
      context: ./nginx
      args:
        UID: $U_ID
    ports:
      - "500:80"
    volumes:
      - ./nginx:/var/log/nginx
    networks:
      - wsmcbl-back-network
    depends_on:
      - wsmcbl-back

  wsmcbl-back:
    container_name: wsmcbl-back
    build:
      context: .
      args:
        UID: $U_ID
    volumes:
      - ./:/www
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    networks:
      - wsmcbl-back-network

networks:
  wsmcbl-back-network:
    external: true