name: Deploy into Somee.com (test)
on:
  push:
    branches: ['develop']
jobs:
  web-deploy:
    name: Desplegar a Somee.com
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3
        
      - name: Run the script deploy.sh
        run: |
          ./deploy.sh
        
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: cblback.somee.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: publish/
          server-dir: /www.cblback.somee.com/